### ISSUE TITLE
getting started?

### ISSUE THREAD

**Issue by jcw** [exupero/turtle#2]
Apologies for asking, but I've only just started on the CLJ/CLJS path, and am only familiar with the `lein figwheel` and `lein cljsbuild` tasks so far. Is there an easy way to try out this project?

**Comment by exupero** [comment]
Hi! Thanks for asking. This library is extracted from [this blog post](http://exupero.org/hazard/post/fractals/). The post uses Klipse, so the fastest way to play with these functions would be to go to that blog post and tinker with the code snippets. They'll re-evaluate automatically and show the results below the code.

The next fastest way would be to just copy the contents of [turtle.core](https://github.com/exupero/turtle/blob/master/src/turtle/core.cljs) into your own codebase.

Ideally, I'd push this up to Clojars so you can pull it in as a dependency, but the code may be too specific to that blog post, and not suitable for others' use cases.

I'm happy to get your feedback. That'll go a long way toward making it general purpose.

**Comment by jcw** [comment]
Many thanks, that'll get me started! You could perhaps set this project's URL on github to point to that blog post, it may help others find their way to it as well.

**Comment by exupero** [comment]
Done. Thanks!
